In [1]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import json
from sklearn.model_selection import train_test_split

device = "cuda"
torch.device(device=device)

torch.manual_seed(42)
torch.cuda.manual_seed(42)
device

'cuda'

In [2]:
LEARNING_RATE = 0.01
HIDDEN_UNITS = 256

In [3]:
data = None
with open('../data/data6.json', 'r') as f:
    data = json.load(f)
data[0], len(data[0][0]), len(data)

([[[0.5011395215988159,
    0.6248122453689575,
    -0.5309008955955505,
    0.999944806098938],
   [0.5169084072113037,
    0.5796157121658325,
    -0.5004986524581909,
    0.9998779296875],
   [0.5265620946884155,
    0.581876277923584,
    -0.500400722026825,
    0.9998977184295654],
   [0.5349892973899841,
    0.5854421854019165,
    -0.5005323886871338,
    0.9998786449432373],
   [0.4825899600982666,
    0.578211784362793,
    -0.5062701106071472,
    0.9998947381973267],
   [0.47005587816238403,
    0.580464243888855,
    -0.5058338642120361,
    0.9999111890792847],
   [0.4582765996456146,
    0.583260178565979,
    -0.5059779286384583,
    0.9998960494995117],
   [0.5458875298500061,
    0.6145269274711609,
    -0.2897486090660095,
    0.9998726844787598],
   [0.4415968358516693,
    0.6105682849884033,
    -0.30674195289611816,
    0.9999305009841919],
   [0.517968475818634,
    0.6900794506072998,
    -0.44951146841049194,
    0.9999161958694458],
   [0.47463616728782654,
  

In [4]:
landmarks = []
labels = []
for pose in data:
  landmarks.append(pose[0])
  labels.append(pose[1])

In [5]:
landmarks = torch.tensor(landmarks, dtype=torch.float).to(device=device)
labels = torch.tensor(labels, dtype=torch.long).to(device=device)
landmarks[0], labels[0]

(tensor([[ 5.0114e-01,  6.2481e-01, -5.3090e-01,  9.9994e-01],
         [ 5.1691e-01,  5.7962e-01, -5.0050e-01,  9.9988e-01],
         [ 5.2656e-01,  5.8188e-01, -5.0040e-01,  9.9990e-01],
         [ 5.3499e-01,  5.8544e-01, -5.0053e-01,  9.9988e-01],
         [ 4.8259e-01,  5.7821e-01, -5.0627e-01,  9.9989e-01],
         [ 4.7006e-01,  5.8046e-01, -5.0583e-01,  9.9991e-01],
         [ 4.5828e-01,  5.8326e-01, -5.0598e-01,  9.9990e-01],
         [ 5.4589e-01,  6.1453e-01, -2.8975e-01,  9.9987e-01],
         [ 4.4160e-01,  6.1057e-01, -3.0674e-01,  9.9993e-01],
         [ 5.1797e-01,  6.9008e-01, -4.4951e-01,  9.9992e-01],
         [ 4.7464e-01,  6.8847e-01, -4.5435e-01,  9.9994e-01],
         [ 6.2768e-01,  9.1637e-01, -1.5847e-01,  9.9847e-01],
         [ 3.3763e-01,  8.9849e-01, -2.3086e-01,  9.9907e-01],
         [ 6.8590e-01,  1.2613e+00, -1.1975e-01,  5.3370e-02],
         [ 2.5005e-01,  1.2171e+00, -2.0391e-01,  1.3901e-01],
         [ 6.9326e-01,  1.5288e+00, -2.6732e-01,  1.571

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(landmarks,
                                                    labels,
                                                    test_size=0.2,
                                                    random_state=42)
Y_train = Y_train.to(device)
Y_test = Y_test.to(device)

X_train[0]

tensor([[ 3.0397e-01,  4.9739e-01, -8.1158e-01,  9.9955e-01],
        [ 3.3119e-01,  4.5101e-01, -8.2172e-01,  9.9932e-01],
        [ 3.5022e-01,  4.4842e-01, -8.2191e-01,  9.9932e-01],
        [ 3.6605e-01,  4.4661e-01, -8.2201e-01,  9.9928e-01],
        [ 2.8816e-01,  4.5434e-01, -7.6942e-01,  9.9938e-01],
        [ 2.7822e-01,  4.5295e-01, -7.6847e-01,  9.9942e-01],
        [ 2.6854e-01,  4.5065e-01, -7.6858e-01,  9.9943e-01],
        [ 4.0048e-01,  4.4773e-01, -6.4268e-01,  9.9915e-01],
        [ 2.7600e-01,  4.5045e-01, -3.6969e-01,  9.9942e-01],
        [ 3.3998e-01,  4.8453e-01, -7.3018e-01,  9.9948e-01],
        [ 2.8986e-01,  4.8228e-01, -6.5313e-01,  9.9954e-01],
        [ 3.6107e-01,  5.2470e-01, -4.4566e-01,  9.9536e-01],
        [ 2.3806e-01,  6.7221e-01, -1.3067e-01,  9.9730e-01],
        [ 4.3862e-01,  8.2719e-01, -4.7985e-01,  4.3046e-01],
        [ 1.8122e-01,  1.0408e+00, -3.5293e-02,  5.9301e-01],
        [ 7.1324e-01,  1.0507e+00, -6.3683e-01,  1.9154e-01],
        

In [7]:
X_test = X_test.view(X_test.size(0), -1)
X_train = X_train.view(X_train.size(0), -1)

In [8]:
model_1 = nn.Sequential(
  nn.Linear(132, HIDDEN_UNITS),
  nn.ReLU(),
  nn.Linear(HIDDEN_UNITS, HIDDEN_UNITS),
  nn.ReLU(),
  nn.Linear(HIDDEN_UNITS, 2)
).to(device=device)
model_1

Sequential(
  (0): Linear(in_features=132, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=256, bias=True)
  (3): ReLU()
  (4): Linear(in_features=256, out_features=2, bias=True)
)

In [9]:
def accuracy_fn(y_true, y_preds):
  correct = torch.eq(y_true, y_preds).sum().item()
  return (correct / len(y_preds)) * 100

In [10]:
loss_fn = nn.CrossEntropyLoss().to(device=device)
optimizer = torch.optim.SGD(model_1.parameters(), lr=LEARNING_RATE)

In [11]:
def logits_to_labels(y_logits):
  y_pred_probs = torch.softmax(y_logits, dim=1)
  y_preds = torch.argmax(y_pred_probs, dim=1)
  return y_preds

In [12]:
X_train[:1], X_test[:1]

(tensor([[ 3.0397e-01,  4.9739e-01, -8.1158e-01,  9.9955e-01,  3.3119e-01,
           4.5101e-01, -8.2172e-01,  9.9932e-01,  3.5022e-01,  4.4842e-01,
          -8.2191e-01,  9.9932e-01,  3.6605e-01,  4.4661e-01, -8.2201e-01,
           9.9928e-01,  2.8816e-01,  4.5434e-01, -7.6942e-01,  9.9938e-01,
           2.7822e-01,  4.5295e-01, -7.6847e-01,  9.9942e-01,  2.6854e-01,
           4.5065e-01, -7.6858e-01,  9.9943e-01,  4.0048e-01,  4.4773e-01,
          -6.4268e-01,  9.9915e-01,  2.7600e-01,  4.5045e-01, -3.6969e-01,
           9.9942e-01,  3.3998e-01,  4.8453e-01, -7.3018e-01,  9.9948e-01,
           2.8986e-01,  4.8228e-01, -6.5313e-01,  9.9954e-01,  3.6107e-01,
           5.2470e-01, -4.4566e-01,  9.9536e-01,  2.3806e-01,  6.7221e-01,
          -1.3067e-01,  9.9730e-01,  4.3862e-01,  8.2719e-01, -4.7985e-01,
           4.3046e-01,  1.8122e-01,  1.0408e+00, -3.5293e-02,  5.9301e-01,
           7.1324e-01,  1.0507e+00, -6.3683e-01,  1.9154e-01,  1.3900e-01,
           1.2737e+00, -4

In [13]:
# Let's get some raw outputs of our model (logits)
model_1.eval()
with torch.inference_mode():
    y_logits = model_1(X_test.to(device=device))

y_logits[:5]

tensor([[-0.0265,  0.0931],
        [-0.0098,  0.0880],
        [-0.0159,  0.0840],
        [-0.0199,  0.0664],
        [-0.0169,  0.0915]], device='cuda:0')

In [14]:
accuracy_fn(y_true=Y_test, y_preds=torch.argmax(torch.softmax(y_logits, dim=1), dim=1))

54.0

In [15]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)

epochs = 15000
train_losses = []
test_losses = []

# GIMME THE DATA
X_train, Y_train = X_train.to(device=device), Y_train.to(device=device)
X_test, Y_test = X_test.to(device=device), Y_test.to(device=device)

previous_test_loss = 100
for epoch in range(epochs):
  model_1.train()

  y_logits = model_1(X_train.to(device=device))
  y_preds = torch.softmax(y_logits, dim=1).argmax(dim=1)

  loss = loss_fn(y_logits, Y_train)
  train_losses.append(loss)
  accuracy = accuracy_fn(y_true=Y_train,
                         y_preds=y_preds)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  model_1.eval()
  with torch.inference_mode():
    test_logits = model_1(X_test)
    test_preds = torch.softmax(test_logits, dim=1).argmax(dim=1)

    test_loss = loss_fn(test_logits, Y_test)
    test_losses.append(test_loss)
    test_accuracy = accuracy_fn(y_true=Y_test,
                                y_preds=test_preds)
    if test_loss > previous_test_loss and test_accuracy >= 80:
      break
    previous_test_loss = test_loss

  if epoch % 10 == 0:
    print(f"Epoch: {epoch} | Train loss: {loss:.4f} | Train accuracy: {accuracy:.2f}% | Test loss: {test_loss:.4f} | Test accuracy: {test_accuracy:.2f}%")

Epoch: 0 | Train loss: 0.6969 | Train accuracy: 48.88% | Test loss: 0.6921 | Test accuracy: 54.00%
Epoch: 10 | Train loss: 0.6928 | Train accuracy: 53.37% | Test loss: 0.6929 | Test accuracy: 52.00%
Epoch: 20 | Train loss: 0.6908 | Train accuracy: 52.88% | Test loss: 0.6930 | Test accuracy: 48.75%
Epoch: 30 | Train loss: 0.6892 | Train accuracy: 51.94% | Test loss: 0.6925 | Test accuracy: 46.25%
Epoch: 40 | Train loss: 0.6879 | Train accuracy: 51.06% | Test loss: 0.6916 | Test accuracy: 45.25%
Epoch: 50 | Train loss: 0.6866 | Train accuracy: 50.62% | Test loss: 0.6906 | Test accuracy: 44.75%
Epoch: 60 | Train loss: 0.6854 | Train accuracy: 50.50% | Test loss: 0.6895 | Test accuracy: 44.75%
Epoch: 70 | Train loss: 0.6842 | Train accuracy: 50.12% | Test loss: 0.6884 | Test accuracy: 44.75%
Epoch: 80 | Train loss: 0.6831 | Train accuracy: 50.25% | Test loss: 0.6873 | Test accuracy: 44.75%
Epoch: 90 | Train loss: 0.6820 | Train accuracy: 51.06% | Test loss: 0.6862 | Test accuracy: 44.75%
E

In [16]:
torch.save(model_1.state_dict(), '../state_dicts/model_2_state_dict.pth')
torch.save(model_1, '../state_dicts/model_2.pth')

In [388]:
X_test[0]

tensor([ 5.7265e-01,  2.3361e-01, -6.5602e-01,  9.9964e-01,  5.7696e-01,
         1.7123e-01, -6.1987e-01,  9.9947e-01,  5.8354e-01,  1.7241e-01,
        -6.1981e-01,  9.9949e-01,  5.8865e-01,  1.7290e-01, -6.2010e-01,
         9.9945e-01,  5.4336e-01,  1.6380e-01, -6.5893e-01,  9.9950e-01,
         5.2683e-01,  1.5928e-01, -6.5901e-01,  9.9954e-01,  5.0885e-01,
         1.5704e-01, -6.5925e-01,  9.9952e-01,  5.7858e-01,  1.9270e-01,
        -3.6450e-01,  9.9936e-01,  4.5994e-01,  1.8073e-01, -5.3987e-01,
         9.9951e-01,  5.7619e-01,  3.0994e-01, -5.5645e-01,  9.9964e-01,
         5.3689e-01,  3.0851e-01, -6.0477e-01,  9.9966e-01,  6.4290e-01,
         6.3952e-01, -1.8650e-01,  9.9744e-01,  2.8198e-01,  5.8836e-01,
        -4.3682e-01,  9.9836e-01,  6.6332e-01,  1.1069e+00, -1.7918e-02,
         4.7958e-01,  1.6111e-01,  1.0364e+00, -3.6281e-01,  5.6680e-01,
         6.6934e-01,  1.5318e+00, -1.5016e-01,  2.0669e-01,  5.7321e-02,
         1.4557e+00, -4.8618e-01,  2.7904e-01,  7.0

In [389]:
# Let's get some raw outputs of our model (logits)
model_1.eval()
with torch.inference_mode():
    y_logits = model_1(X_test.to(device=device))

y_logits[:5]

tensor([[-0.3545,  0.4107],
        [-1.7361,  1.7720],
        [-0.2593,  0.2990],
        [ 0.0445, -0.0148],
        [-0.7966,  0.8317]], device='cuda:0')

In [390]:
torch.tensor([5, 5, 5]).unsqueeze(0)

tensor([[5, 5, 5]])

In [391]:
y_preds_probs = torch.softmax(y_logits, dim=1)
y_preds_probs

tensor([[3.1752e-01, 6.8248e-01],
        [2.9083e-02, 9.7092e-01],
        [3.6393e-01, 6.3607e-01],
        [5.1482e-01, 4.8518e-01],
        [1.6406e-01, 8.3594e-01],
        [3.1973e-02, 9.6803e-01],
        [9.7332e-01, 2.6678e-02],
        [1.2089e-02, 9.8791e-01],
        [3.9711e-01, 6.0289e-01],
        [7.8843e-02, 9.2116e-01],
        [6.7932e-02, 9.3207e-01],
        [9.7060e-02, 9.0294e-01],
        [2.5681e-02, 9.7432e-01],
        [1.3878e-02, 9.8612e-01],
        [3.7185e-02, 9.6281e-01],
        [2.6783e-02, 9.7322e-01],
        [7.1436e-01, 2.8564e-01],
        [3.3100e-01, 6.6900e-01],
        [8.9109e-01, 1.0891e-01],
        [1.3566e-01, 8.6434e-01],
        [3.8780e-01, 6.1220e-01],
        [2.3124e-01, 7.6876e-01],
        [4.4914e-02, 9.5509e-01],
        [3.4428e-01, 6.5572e-01],
        [1.6765e-02, 9.8323e-01],
        [4.1119e-02, 9.5888e-01],
        [8.6826e-01, 1.3174e-01],
        [6.9169e-01, 3.0831e-01],
        [4.7984e-01, 5.2016e-01],
        [5.359

In [392]:
values = set()
for probs in y_preds_probs:
  values.add(torch.argmax(probs).item())
  print(torch.argmax(probs))
values

tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')
tensor(0, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')
t

{0, 1}

In [17]:
dummy_inputs = torch.randn(1, 132).to(device=device)
onnx_program = torch.onnx.export(model_1,
                                 dummy_inputs,
                                 "../onnx/model4.onnx",
                                 export_params=True,
                                 do_constant_folding=True,
                                 input_names=['input'],
                                 output_names=['output'])