In [1]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import json
from sklearn.model_selection import train_test_split

device = "cuda"
torch.device(device=device)

torch.manual_seed(42)
torch.cuda.manual_seed(42)
device

'cuda'

In [2]:
LEARNING_RATE = 0.002
HIDDEN_UNITS = 32

In [3]:
data = None
with open('data2.json', 'r') as f:
    data = json.load(f)
data[0], len(data[0][0]), len(data)

([[[0.45497363805770874,
    0.40181559324264526,
    -0.10442516207695007,
    0.9964860677719116],
   [0.46596378087997437,
    0.3687018156051636,
    -0.14153742790222168,
    0.9968416690826416],
   [0.47041770815849304,
    0.36795997619628906,
    -0.141709566116333,
    0.9973503351211548],
   [0.4751827120780945,
    0.3672834634780884,
    -0.14179515838623047,
    0.9976590871810913],
   [0.4611609876155853,
    0.3686749339103699,
    -0.0905613824725151,
    0.9964673519134521],
   [0.46208521723747253,
    0.3676823377609253,
    -0.09063052386045456,
    0.9964346885681152],
   [0.46336010098457336,
    0.36653953790664673,
    -0.09079504758119583,
    0.9968423843383789],
   [0.50380539894104,
    0.3792932629585266,
    -0.2224762737751007,
    0.9974061846733093],
   [0.4925134778022766,
    0.37584102153778076,
    0.0051500811241567135,
    0.9974742531776428],
   [0.4672686755657196,
    0.43053245544433594,
    -0.12731407582759857,
    0.9970880150794983],
   [0

In [4]:
landmarks = []
labels = []
for pose in data:
  landmarks.append(pose[0])
  labels.append(pose[1])

In [5]:
landmarks = torch.tensor(landmarks, dtype=torch.float).to(device=device)
labels = torch.tensor(labels, dtype=torch.long).to(device=device)
landmarks[0], labels[0]

(tensor([[ 0.4550,  0.4018, -0.1044,  0.9965],
         [ 0.4660,  0.3687, -0.1415,  0.9968],
         [ 0.4704,  0.3680, -0.1417,  0.9974],
         [ 0.4752,  0.3673, -0.1418,  0.9977],
         [ 0.4612,  0.3687, -0.0906,  0.9965],
         [ 0.4621,  0.3677, -0.0906,  0.9964],
         [ 0.4634,  0.3665, -0.0908,  0.9968],
         [ 0.5038,  0.3793, -0.2225,  0.9974],
         [ 0.4925,  0.3758,  0.0052,  0.9975],
         [ 0.4673,  0.4305, -0.1273,  0.9971],
         [ 0.4614,  0.4322, -0.0613,  0.9933],
         [ 0.5282,  0.5542, -0.3417,  0.9962],
         [ 0.5174,  0.5378,  0.1624,  0.9910],
         [ 0.4037,  0.7270, -0.3720,  0.9829],
         [ 0.4990,  0.7079,  0.3016,  0.0581],
         [ 0.2496,  0.7240, -0.2466,  0.9607],
         [ 0.4708,  0.8202,  0.2938,  0.0619],
         [ 0.2057,  0.7512, -0.2833,  0.9475],
         [ 0.4713,  0.8505,  0.3012,  0.0787],
         [ 0.1976,  0.7324, -0.2591,  0.9493],
         [ 0.4695,  0.8383,  0.2614,  0.0816],
         [ 0.

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(landmarks,
                                                    labels,
                                                    test_size=0.1,
                                                    random_state=42)
Y_train = Y_train.to(device)
Y_test = Y_test.to(device)

X_train[0]

tensor([[ 6.0004e-01,  2.7288e-01, -5.5688e-01,  9.9998e-01],
        [ 6.2263e-01,  2.2191e-01, -5.0372e-01,  9.9996e-01],
        [ 6.3562e-01,  2.2268e-01, -5.0357e-01,  9.9995e-01],
        [ 6.4750e-01,  2.2405e-01, -5.0354e-01,  9.9995e-01],
        [ 5.7685e-01,  2.2046e-01, -5.2242e-01,  9.9996e-01],
        [ 5.5728e-01,  2.2040e-01, -5.2219e-01,  9.9997e-01],
        [ 5.3982e-01,  2.2126e-01, -5.2251e-01,  9.9997e-01],
        [ 6.6165e-01,  2.5981e-01, -2.1694e-01,  9.9992e-01],
        [ 5.1162e-01,  2.5241e-01, -2.9134e-01,  9.9998e-01],
        [ 6.2057e-01,  3.4072e-01, -4.5439e-01,  9.9997e-01],
        [ 5.6577e-01,  3.3901e-01, -4.7465e-01,  9.9998e-01],
        [ 7.3370e-01,  6.2859e-01, -3.7083e-02,  9.9957e-01],
        [ 4.0588e-01,  5.9883e-01, -3.0429e-01,  9.9989e-01],
        [ 7.7472e-01,  9.6900e-01,  4.6307e-02,  3.6405e-01],
        [ 3.8907e-01,  9.8291e-01, -3.2129e-01,  5.5738e-01],
        [ 8.2213e-01,  1.3009e+00, -1.7229e-01,  4.7496e-02],
        

In [7]:
X_test = X_test.view(X_test.size(0), -1)
X_train = X_train.view(X_train.size(0), -1)

In [13]:
model_1 = nn.Sequential(
  nn.Linear(132, HIDDEN_UNITS),
  nn.ReLU(),
  nn.Linear(HIDDEN_UNITS, HIDDEN_UNITS),
  nn.ReLU(),
  nn.Linear(HIDDEN_UNITS, 2)
).to(device=device)
model_1

Sequential(
  (0): Linear(in_features=132, out_features=32, bias=True)
  (1): ReLU()
  (2): Linear(in_features=32, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=2, bias=True)
)

In [14]:
def accuracy_fn(y_true, y_preds):
  correct = torch.eq(y_true, y_preds).sum().item()
  return (correct / len(y_preds)) * 100

In [15]:
loss_fn = nn.CrossEntropyLoss().to(device=device)
optimizer = torch.optim.SGD(model_1.parameters(), lr=LEARNING_RATE)

In [16]:
def logits_to_labels(y_logits):
  y_pred_probs = torch.softmax(y_logits, dim=1)
  y_preds = torch.argmax(y_pred_probs, dim=1)
  return y_preds

In [17]:
X_train[:1], X_test[:1]

(tensor([[ 6.0004e-01,  2.7288e-01, -5.5688e-01,  9.9998e-01,  6.2263e-01,
           2.2191e-01, -5.0372e-01,  9.9996e-01,  6.3562e-01,  2.2268e-01,
          -5.0357e-01,  9.9995e-01,  6.4750e-01,  2.2405e-01, -5.0354e-01,
           9.9995e-01,  5.7685e-01,  2.2046e-01, -5.2242e-01,  9.9996e-01,
           5.5728e-01,  2.2040e-01, -5.2219e-01,  9.9997e-01,  5.3982e-01,
           2.2126e-01, -5.2251e-01,  9.9997e-01,  6.6165e-01,  2.5981e-01,
          -2.1694e-01,  9.9992e-01,  5.1162e-01,  2.5241e-01, -2.9134e-01,
           9.9998e-01,  6.2057e-01,  3.4072e-01, -4.5439e-01,  9.9997e-01,
           5.6577e-01,  3.3901e-01, -4.7465e-01,  9.9998e-01,  7.3370e-01,
           6.2859e-01, -3.7083e-02,  9.9957e-01,  4.0588e-01,  5.9883e-01,
          -3.0429e-01,  9.9989e-01,  7.7472e-01,  9.6900e-01,  4.6307e-02,
           3.6405e-01,  3.8907e-01,  9.8291e-01, -3.2129e-01,  5.5738e-01,
           8.2213e-01,  1.3009e+00, -1.7229e-01,  4.7496e-02,  3.4676e-01,
           1.3536e+00, -6

In [18]:
# Let's get some raw outputs of our model (logits)
model_1.eval()
with torch.inference_mode():
    y_logits = model_1(X_test.to(device=device))

y_logits[:5]

tensor([[-0.3416,  0.2226],
        [-0.3526,  0.2348],
        [-0.2777,  0.1344],
        [-0.2568,  0.1876],
        [-0.3119,  0.2079]], device='cuda:0')

In [19]:
accuracy_fn(y_true=Y_test, y_preds=torch.argmax(torch.softmax(y_logits, dim=1), dim=1))

38.88888888888889

In [ ]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)

epochs = 15000
train_losses = []
test_losses = []

# GIMME THE DATA
X_train, Y_train = X_train.to(device=device), Y_train.to(device=device)
X_test, Y_test = X_test.to(device=device), Y_test.to(device=device)

previous_test_loss = 100
for epoch in range(epochs):
  model_1.train()

  y_logits = model_1(X_train.to(device=device))
  y_preds = torch.softmax(y_logits, dim=1).argmax(dim=1)

  loss = loss_fn(y_logits, Y_train)
  train_losses.append(loss)
  accuracy = accuracy_fn(y_true=Y_train,
                         y_preds=y_preds)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  model_1.eval()
  with torch.inference_mode():
    test_logits = model_1(X_test)
    test_preds = torch.softmax(test_logits, dim=1).argmax(dim=1)

    test_loss = loss_fn(test_logits, Y_test)
    test_losses.append(test_loss)
    test_accuracy = accuracy_fn(y_true=Y_test,
                                y_preds=test_preds)
    if test_loss > previous_test_loss and test_accuracy >= 80:
      break
    previous_test_loss = test_loss

  if epoch % 10 == 0:
    print(f"Epoch: {epoch} | Train loss: {loss:.4f} | Train accuracy: {accuracy:.2f}% | Test loss: {test_loss:.4f} | Test accuracy: {test_accuracy:.2f}%")

RuntimeError: Expected floating point type for target with class probabilities, got Long

In [21]:
import matplotlib.pyplot as plt
test_losses = [x.detach().cpu().numpy() for x in test_losses]
plt.plot(test_losses)

ModuleNotFoundError: No module named 'matplotlib.backends.registry'

In [ ]:
torch.save(model_1.state_dict(), 'model_1_state_dict.pth')
torch.save(model_1, 'model_1.pth')

In [ ]:
X_test[0]

tensor([ 0.7019,  0.2358, -0.0794,  0.9998,  0.7011,  0.2034, -0.0620,  0.9998,
         0.6999,  0.2022, -0.0622,  0.9998,  0.6983,  0.2009, -0.0624,  0.9998,
         0.6988,  0.2023, -0.1077,  0.9997,  0.6961,  0.2005, -0.1077,  0.9997,
         0.6932,  0.1987, -0.1077,  0.9997,  0.6742,  0.1987,  0.0256,  0.9999,
         0.6694,  0.1976, -0.1785,  0.9998,  0.6880,  0.2590, -0.0437,  0.9997,
         0.6855,  0.2563, -0.1024,  0.9998,  0.5970,  0.2984,  0.1479,  0.9993,
         0.5997,  0.3287, -0.2754,  0.9997,  0.6287,  0.5036,  0.1889,  0.0989,
         0.6273,  0.5535, -0.2845,  0.9631,  0.7057,  0.6203,  0.1053,  0.0942,
         0.7434,  0.6629, -0.1462,  0.8975,  0.7379,  0.6672,  0.0953,  0.1081,
         0.7688,  0.7033, -0.1729,  0.8593,  0.7452,  0.6669,  0.0584,  0.1124,
         0.7753,  0.6877, -0.1553,  0.8632,  0.7295,  0.6339,  0.0836,  0.1196,
         0.7659,  0.6732, -0.1385,  0.8468,  0.5341,  0.6013,  0.1221,  0.9829,
         0.5340,  0.6545, -0.1218,  0.99

In [ ]:
# Let's get some raw outputs of our model (logits)
model_0.eval()
with torch.inference_mode():
    y_logits = model_0(X_test.to(device=device))

y_logits[:5]

tensor([[-0.4176,  0.3001],
        [-1.7784,  1.7537],
        [ 1.4930, -1.7860],
        [-0.9521,  0.8326],
        [ 2.6078, -3.0149]], device='cuda:0')

In [ ]:
y_preds_probs = torch.softmax(y_logits, dim=1)
y_preds_probs

tensor([[0.3279, 0.6721],
        [0.0284, 0.9716],
        [0.9637, 0.0363],
        [0.1437, 0.8563],
        [0.9964, 0.0036],
        [0.9948, 0.0052],
        [0.5000, 0.5000],
        [0.1282, 0.8718],
        [0.1083, 0.8917],
        [0.9526, 0.0474]], device='cuda:0')

In [ ]:
values = set()
for probs in y_preds_probs:
  values.add(torch.argmax(probs).item())
  print(torch.argmax(probs))
values

tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')
tensor(0, device='cuda:0')
tensor(0, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(0, device='cuda:0')


{0, 1}

In [ ]:
dummy_inputs = torch.randn(1, 132).to(device=device)
onnx_program = torch.onnx.export(model_1,
                                 dummy_inputs,
                                 "model2.onnx",
                                 export_params=True,
                                 do_constant_folding=True,
                                 input_names=['input'],
                                 output_names=['output'])